CMSIS-NN: Add support for null bias for Fully Connected op
ARM-software/CMSIS_5 pull request #1108
Opened 2021-01-26 07:40 UTC by felix-johnny

NULL bias support is added for Fully Connected op
for  processors with and without DSP extension.

Added Test case to verify it

Also contribution by @mansnils

2021-01-26 07:41 UTC, felix-johnny commented
@mansnils Could you review this?

2021-01-26 08:02 UTC, mansnils requested changes
batches was missing here. it should be batches before generate_bias.
..., batches, generate_bias) should be enough

2021-01-26 08:05 UTC, mansnils commented on CMSIS/NN/Tests/UnitTest/generate_test_data.py
> -                         randmax, outminrange, outmaxrange, batches)
This is the place I ment..
batches was missing here. it should be batches before generate_bias.
..., batches, generate_bias) should be enough

2021-01-27 12:41 UTC, mansnils approved these changes

2021-01-27 12:44 UTC, merged