RTX5 irq_armv7m.s forgot to cover FPv5_D16 and FPv5_SP_D15
ARM-software/CMSIS_5 pull request #1267
Opened 2021-07-28 22:14 UTC by GorgonMeducer

I am not the first person who found this issue:

I observed the issue in a Chinese bbs:
http://www.armbbs.cn/forum.php?mod=viewthread&tid=108052&highlight=CMSIS

The first reporter is eric2013, who is the owner of this bbs.
Since I have confirmation that he doesn't have a GitHub account, and he explicitly suggested that the arm open-source community should fix this, I create this patch.

2021-07-28 22:19 UTC, grasci-arm commented
Can one of the admins verify this patch?

2021-07-29 07:47 UTC, JonatanAntoni requested changes
Thanks for raising this as a PR.
This issue is already discussed in #1266.

2021-07-29 07:47 UTC, JonatanAntoni commented on CMSIS/RTOS2/RTX/Source/ARM/irq_armv7m.s
> +                IF       ({FPU}="FPv4-SP") || ({FPU}="FPv5_D16") || ({FPU}="FPv5_SP_D16")
Please double check with #1266.

2021-07-29 08:31 UTC, JonatanAntoni commented
@GorgonMeducer, may I ask you to properly rebase your pull-request, please? I'd expect it only lists a single commit introducing the fix. Merge commits easily cause issues when merging the PR.

2021-07-29 10:59 UTC, GorgonMeducer commented
> @GorgonMeducer, may I ask you to properly rebase your pull-request, please? I'd expect it only lists a single commit introducing the fix. Merge commits easily cause issues when merging the PR.

OK, will do that next time.

2021-07-29 10:59 UTC, closed without merging