DSP: Eliminate some non-standard C code and some initial IAR support
ARM-software/CMSIS_5 pull request #1314
Opened 2021-09-21 14:43 UTC by TTornblom

2021-09-21 14:44 UTC, grasci-arm commented
Can one of the admins verify this patch?

2021-09-24 05:13 UTC, christophe0606 requested changes
Hi @TTornblom 

I'll merge the pull request when I have checked there is no build issues with other configurations.

And I'll probably report you the problems to correct one after another. I'll try to build and if the build is failing, I report you the problem.

After a few iterations of the process everything should be ok.

2021-09-24 07:42 UTC, TTornblom commented on CMSIS/DSP/PrivateInclude/arm_vec_fft.h
> +#define MVE_CMPLX_MULT_FX_AxB(A,B,TyA)      vqdmladhxq(vqdmlsdhq((TyA)vuninitializedq_s32(), A, B), A, B)
Sorry about that. Do you have instructions on how to build that, so I can test and fix?

2021-09-24 08:09 UTC, christophe0606 commented on CMSIS/DSP/PrivateInclude/arm_vec_fft.h
> +#define MVE_CMPLX_MULT_FX_AxB(A,B,TyA)      vqdmladhxq(vqdmlsdhq((TyA)vuninitializedq_s32(), A, B), A, B)
I can do the builds. No problem with that. But it may require a few iterations between us.

2021-09-27 07:09 UTC, TTornblom commented on CMSIS/DSP/PrivateInclude/arm_vec_fft.h
> +#define MVE_CMPLX_MULT_FX_AxB(A,B,TyA)      vqdmladhxq(vqdmlsdhq((TyA)vuninitializedq_s32(), A, B), A, B)
This has become a bit messy. I'll close this PR and clean things up and create a new one

2021-09-27 07:09 UTC, closed without merging

2021-09-27 07:10 UTC, TTornblom commented
Will clean things up and create a new PR

2021-09-27 07:11 UTC, christophe0606 commented
@TTornblom  Ok. But I was just validating this one and so far I have found no issues.
So I should be able to merge the other PR quickly.