Corrected link script issue with gcc for pack ARMCA5, ARMCA7 and ARMCA9.
ARM-software/CMSIS_5 pull request #1522
Opened 2022-07-12 07:54 UTC by christophe0606

Corrected little issue in the pack description for ARMCA5, CA7 and CA9 for gcc.

2022-07-12 07:59 UTC, grasci-arm commented
Can one of the admins verify this patch?

2022-07-18 13:42 UTC, JonatanAntoni requested changes

2022-07-18 13:42 UTC, JonatanAntoni commented on ARM.CMSIS.pdsc
> +        <file category="linkerScript"        name="Device/ARM/ARMCA5/Source/GCC/ARMCA5.ld"        version="1.0.0" attr="config" condition="GCC"/>
Please reorder the whitespace to keep the columns.

2022-07-18 13:52 UTC, christophe0606 commented on ARM.CMSIS.pdsc
> +        <file category="linkerScript"        name="Device/ARM/ARMCA5/Source/GCC/ARMCA5.ld"        version="1.0.0" attr="config" condition="GCC"/>
I have pushed the fix.

2022-07-21 06:56 UTC, brondani approved these changes

2022-07-21 07:01 UTC, merged