Adding MPU macros and improving docs
ARM-software/CMSIS_5 pull request #1617
Opened 2023-04-10 15:09 UTC by M-Plichta

Functional changes:
- There already were macros for MPU_RBAR shareability field (`ARM_MPU_SH_NON`, `ARM_MPU_SH_OUTER` and `ARM_MPU_SH_INNER`), so I added macros for the access permissions and execute-never fields.
- Added some handy functions and macros for better readability, like `ARM_MPU_TYPE` function and the macro `MAIR_ATTR`.
- Added input macros for `ARM_MPU_ATTR`

Docs:
- Changed wording for clarity and consistency with the Architecture Reference Manual.

2023-04-10 15:11 UTC, M-Plichta commented
If the changes are accepted, examples will have to be changes, like the ones in `Ref_MPU8.txt`

2023-04-10 15:14 UTC, grasci-arm commented
Can one of the admins verify this patch?

2023-04-11 10:53 UTC, EdmundPlayer commented on CMSIS/Core/Include/mpu_armv8.h
Looks good - we could perhaps change the wording slightly for the comments, so that they align with the capitlisation as per the Armv8-M Architecture.

* \param NT Non-Transient: Set to 1 for non-transient data. Set to 0 for transient data.
* \param WB Write-Back: Set to 1 to use write-back update policy. Set to 0 to use non-write-back update policy.
* \param RA Read Allocation: Set to 1 to use cache allocation on read miss. Set to 0 to not use cache allocation on read miss.
* \param WA Write Allocation: Set to 1 to use cache allocation on write miss. Set to 0 to not use cache allocation on write miss.

to:

* \param NT Non-Transient: Set to 1 for Non-transient data. Set to 0 for Transient data.
* \param WB Write-Back: Set to 1 to use a Write-Back policy. Set to 0 to use a Write-Through policy.
* \param RA Read Allocation: Set to 1 to enable cache allocation on read miss. Set to 0 to disable cache allocation on read miss.
* \param WA Write Allocation: Set to 1 to enable cache allocation on write miss. Set to 0 to disable cache allocation on write miss.

2023-04-11 11:06 UTC, M-Plichta commented on CMSIS/Core/Include/mpu_armv8.h
Thanks for the comments, added a new version reflecting the changes.

2023-04-11 11:22 UTC, GuentherMartin requested changes
Please update version and date in the header section.

2023-04-12 08:18 UTC, M-Plichta commented
Hey @GuentherMartin, thanks for the comment.

What's wrong with the CoreValidation test?
This is my first pull request so I can't quite work out why it's failing.

Thanks

2023-04-13 09:08 UTC, merged

2023-04-13 09:10 UTC, GuentherMartin commented
Hello @M-Plichta, there are some problems within the test environment. I will try to run the tests manually.