IRQn_Type: Ensure enum size matches maximum value.
ARM-software/CMSIS_5 pull request #1624
Opened 2023-05-01 22:19 UTC by axel-simon

This change fixes a bug where a compiler choses a signed byte to store the IRQn_Type enum type as all listed enum values fit a signed byte. This causes undefined behavior when calling functions such as NVIC_EnableIRQ with interrupt channels greater than 127 as these do not fit a signed byte. As a result, interrupt channels higher than 127 cannot be enabled, disabled, or triggered.

Fix this by listing the highest possible interrupt channel in each enum declaration which ensures that a storage type is chosen that can accommodate all valid interrupt channels.

Tested on a MEC1527 devices by triggering interrupt channel 171 (watchdog) and observing that the ISR is executed.

2023-05-01 22:24 UTC, grasci-arm commented
Can one of the admins verify this patch?

2023-05-02 07:21 UTC, JonatanAntoni requested changes
Can we keep the enum members `Interrupt1_IRQn` to `Interrupt9_IRQn`, please?
They might be used by test applications. Removing existing declarations would be a breaking change we should avoid.

Please take care about the file headers and update the versions (increment patch level) and dates.

2023-05-03 11:42 UTC, JonatanAntoni approved these changes

2023-05-03 11:43 UTC, merged

2023-05-03 13:14 UTC, axel-simon commented
Thank you for the quick turnaround!