Add implementation of SVDF kernel.
ARM-software/CMSIS_5 pull request #987
Opened 2020-08-24 14:43 UTC by jenselofsson

Optimized version of the SVDF-kernel compatible with TensorFlow Lite Micro.

2020-08-25 11:05 UTC, jenselofsson commented
Fixed in https://github.com/tensorflow/tensorflow/pull/42651

2020-08-27 09:55 UTC, felix-johnny requested changes

2020-08-27 09:55 UTC, felix-johnny commented on CMSIS/NN/Source/SVDFunctions/arm_svdf_s8.c
> +      int32_t sum = 0;
Please fix the redefinition of sum.

2020-08-27 09:55 UTC, felix-johnny commented on CMSIS/NN/Source/SVDFunctions/arm_svdf_s8.c
> +  const int32_t unit_cnt = feature_batches / rank;
please use count here instead of cnt

2020-08-27 10:49 UTC, jenselofsson commented on CMSIS/NN/Source/SVDFunctions/arm_svdf_s8.c
> +      int32_t sum = 0;
Done.

2020-08-27 10:51 UTC, jenselofsson commented on CMSIS/NN/Source/SVDFunctions/arm_svdf_s8.c
> +  const int32_t unit_cnt = feature_batches / rank;
Done.

2020-08-27 14:35 UTC, jenselofsson commented on CMSIS/NN/Include/arm_nnfunctions.h
> +     *                          Range of svdf_params->input_offset  : [-127, 128]
Correct, when I double check it I realize I've simply mistyped it.

2020-08-27 14:57 UTC, jenselofsson commented on CMSIS/NN/Include/arm_nnfunctions.h
> +     * @param[in]   input_quant_params Input quantization parameters
The "Range of svdf_params..." describes the svdf_params argument. Should I the two lines above line 2075 instead?

2020-08-28 09:53 UTC, felix-johnny approved these changes

2020-08-28 09:53 UTC, merged